id: PB6B0B17F
initial_creation_type: ocr
source_metadata:
  volumes:
    b10410c71243430a9eedfa4bfa02ec6f:
      base_file: v027.txt
      image_group_id: I1PD95872
      title: ཏིང་ངེ་འཛིན་གྱི་ཚོགས་ཀྱི་ལེའུ།
      total_pages: 1953
      volume_number: 27
